# Generated by Django 2.1.8 on 2019-11-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_auto_20191104_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycar',
            name='goods_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buycar',
            name='goods_name',
            field=models.TextField(),
        ),
    ]
