# Generated by Django 2.1.8 on 2019-10-31 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_goods_goods_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QUser.Quser'),
        ),
    ]
