# Generated by Django 2.1.8 on 2019-11-05 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QUser', '0003_goodsaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsaddress',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='QUser.Quser'),
        ),
    ]
